### ISSUE TITLE
[bug] Invalid error message when target is not on the network 

### ISSUE THREAD

**Issue by p0dalirius** [Processus-Thief/HEKATOMB#1]
![image](https://user-images.githubusercontent.com/79218792/190875267-8288d16a-c193-4e0a-920e-bdf70dd0bd89.png)

I think there should be a specific message for when the target is not reachable, different from an "invalid credentials" message

**Comment by Processus-Thief** [comment]
I will check that ;)
First, the script will try to connect on DC on c$ share and if it can't access it, it prints this message.
I can try to ping the host first and see if it's available or not but it depends on firewall status if it permits ICMP response...
Thanks for your help ;)
