### ISSUE TITLE
Coucou !

### ISSUE THREAD

**Issue by 0xPreDa** [Processus-Thief/HEKATOMB#10]
Je t'emprunte ton repo pour mon exam de SecOff.
J'espère que tu m'en voudra pas :p 

Pour les autres le mdp que vous cherchez est le suivant : Thisisanotherstrongpassword

Keur sur toi Proc <3

**Comment by Processus-Thief** [comment]
Hahaha fais-toi plaisir ! 😘
Si t'a des questions hésite pas 😉 ça sera avec plaisir
