### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by adioziaete** [Processus-Thief/HEKATOMB#15]
From Kali in workgroup
Testing admin rights...
Admin access granted.
Testing LDAP connection...
Error : Could not connect to ldap with SSL encryption. Trying without SSL encryption...
LDAP connection successfull without encryption.
[+] Retrieving user objects in LDAP directory...
Converting ObjectSID in string SID...
Found about 348 users in LDAP directory.
[+] Retrieving computer objects in LDAP directory...
Found about 121 computers in LDAP directory.
[+] Creating structure folders to store blob and mkf...
[+] Scanning computers list on SMB port ...
It seems that 0 computers are online ...
[+] Connnecting to all computers and try to get dpapi blobs and masteles ...
ZeroDivisionError: float division by zero

**Comment by Processus-Thief** [comment]
-> 0 computers are online

check computers firewall or network access to computers, you can't reach them
A check on the amount of computers has been added to the source code to prevent the crash ;)
Thank for your notice
